---
title: "hw01-josh-seo"
author: "Josh Seo"
date: "2/23/18"
output: github_document
---


##HW1_Part 2: Data Import
```{r}
library(readr)

#vector of column names
column_names <- c('symboling', 
                  'normalized-losses', 
                  'make', 'fuel_type', 
                  'aspiration', 
                  'num_of_doors', 
                  'body_style', 
                  'drive_wheels', 
                  'engine_location', 
                  'wheel_base', 
                  'length', 
                  'width', 
                  'height', 
                  'curb_weight', 
                  'engine_type', 
                  'num_of_cylinders', 
                  'engine_size', 
                  'fuel_system', 
                  'bore', 
                  'stroke', 
                  'compression_ratio', 
                  'horsepower', 
                  'peak_rpm', 
                  'city_mpg',
                  'highway_mpg', 
                  'price')

#vector of column types
column_types <- c('double',
                  'double',
                  'character',
                  'character',
                  'character',
                  'character',
                  'character',
                  'character',
                  'character',
                  'double',
                  'double',
                  'double',
                  'double',
                  'integer',
                  'character',
                  'character',
                  'integer',
                  'character',
                  'double',
                  'double',
                  'double',
                  'integer',
                  'integer',
                  'integer',
                  'integer',
                  'integer')

#import using read.csv
imports85_2 <- read.csv (file = 'imports-85.data',
                         header = TRUE, 
                         col.names = column_names, 
                         colClasses = column_types, 
                         sep = ",", 
                         na = "?")
str(imports85_2, vec.len=1)

#import using read_csv
imports85_2 <- read_csv("imports-85.data",  
          col_names = column_names,
          col_types = list(
           'symboling' = col_double(),
           'normalized_losses' = col_character(),
           'make' = col_character(), 
           'fuel_type' = col_character(),
           'aspiration' = col_character(), 
           'num_of_doors' = col_character(),
           'body_style' = col_character(),
           'drive_wheels' = col_character(),
           'engine_location' = col_character(),
           'wheel_base' = col_double(),
           'length' = col_double(),
           'width' = col_double(),
           'height' = col_double(),
           'curb_weight' = col_integer(),
           'engine_type' = col_character(),
           'num_of_cylinders' = col_character(),
           'engine_size' = col_integer(),
           'fuel_system' = col_character(),
           'bore' = col_double(),
           'stroke' = col_double(),
           'compression_ratio' = col_double(),
           'horsepower' = col_integer(),
           'peak_rpm' = col_integer(),
           'city_mpg' = col_integer(),
           'highway_mpg' = col_integer(),
           'price' = col_integer()
                         ),
          na = "?"
        )
str(imports85_2, vec.len=1)
```


##HW1_Part 3: Technical Questions - Importing Data
```{r}
#   a. If we do not define any column names and import a data using read.csv, it does not show the column names.It prints just the data.
#   b. If we do not define any column nammes and import a data using read.csv with the header=FALSE, it prints the vector number on the top of each column as in forms of V1, V2,...
#   c. If we do not specify how missing values are codified when reading the table functions, it will keep its value as "?" and it will cause errors when using functions with the data.
#   d. Not as told in the question, when tested, the data imported with column types specified had smaller object size than the data with column types not specified. We can assume that assigning integer type to a value with double value would limit and decrease the size of the data.
#   e. If the data frame 'dat' is converted into a R matrix, then the data frame will be come an array with certain degree with numeric values. 
```


##HW1_Part 4: Practice Base Plotting
```{r}
#historgram
colors <- c("red", "blue", "green", "yellow", 
            "cyan", "magenta", "black", "white", "purple")
hist(imports85_2$price, col=colors)

#box-plot
boxplot(imports85_2$horsepower, 
        data = imports85_2, 
        horizontal = TRUE, 
        main = "Horsepower of Automobile", 
        xlab = "Automobile", 
        ylab = "HP")

typeof(imports85_2$horsepower)
summary(imports85_2$horsepower)

#bar-plot
count <- sort(table(imports85_2$body_style), decreasing = TRUE)
barplot(count,
        main="Body Style Frequency", 
        xlab = "Body Style",
        ylab = "Frequency"
        )

#stars-plot
turbo.data <- data.frame(imports85_2[imports85_2$aspiration == "turbo",])
stars(turbo.data[c(10:13, 26)], locations = NULL, len=1, key.loc = c(18,10),
      key.labels = c("wheel_base", "length", "width", "height", "price"),
      scale = TRUE, radius  =  TRUE, full = TRUE,
      col.segments = 1:5, col.stars = NA, col.lines = NA,
      main = "Turbo Summary")
```


##HW1_Part 5: Summaries
```{r}
#What is the mean price of fuel_type gas cars?
mean(imports85_2$price[imports85_2$fuel_type=="gas"], na.rm = TRUE)
                         
#What is the mean price of fuel_type diesel cars?
mean(imports85_2$price[imports85_2$fuel_type=="diesel"], na.rm = TRUE)
  
#What is the make of the car with twelve num_of_cylinders?
imports85_2$make[imports85_2$num_of_cylinders == "twelve"]

#What is the price of the car with the largest amount of hoursepower?
imports85_2$price[max(imports85_2$horsepower, na.rm = TRUE)]

#what is the bottom 10th percentile of city_mpg?
quantile(imports85_2$city_mpg, 0.1)

#what is the top 10th percentile of highway_mpg?
quantile(imports85_2$highway_mpg, 0.9)

#what is the median price of those cars in the bottom 10th percentile of city_mpg?
Bottom10_citympg.data <- data.frame(
  imports85_2[imports85_2$city_mpg <= quantile(imports85_2$city_mpg, 0.1),]
  )
median(Bottom10_citympg.data$price, na.rm = TRUE)
```


##HW1_Part 6: Technical Questions - Data Frames
```{r}
#    a. If you attempt to use names that do not exist after the $ operator, it returns NULL
#    b. 4. mtcars[ ,mpg] fails to return, because the vector mpg is not written in the quotes("").
#    c. For a data frame [] the bracket is single square operator. two coordinates separated by comma thus cell value from first column = 1 numeric coordinate use "mpg". [[]] is to select single element
#    d. YES. When we assign names to the column, we can either use c() or list() to combine the list of more than one names we want to give to the columns at once. But the order is very important, as it counts the order by the vector number.
#    e. as.list gives TRUE or FALSE value to the names. So, if you do not specify, it would return error regarding false values.
#    f. Use as.data.frame(abc)
    
```


##HW1_Part 7: Correlations of quantitative variables
```{r}
library(stats)
library(corrplot)
qdat <- na.omit(imports85_2[-c(1:9, 15, 16, 18)])
Q <- cor(qdat)

#Correlogram 1
corrplot.mixed(Q, lower = "number", upper = "color", lower.col = "pink", number.cex = .7)

#Correlogram 1
corrplot(Q, method = "circle", order = "hclust", tl.col = "green", tl.srt = 45, bg = "lavender")

#We can replace "lower" or "upper" with "color", "number", "pie", "circle", etc. If "lower" is a number, number.cex returns the size of it. You can change or assign a color with "lower.col".

#It seems like some variables (i.e. rpm, mpg's) have strong negative correlations as shown in red, while all other values except stroke and compression ration have strong positive correlations as shown in blue. The two excetions in white do not have strong correlations.
```



##HW1_Part 8: Principal Components Analysis
```{r}
#Run PCA
#Ref: "stats:::print.summary.princomp"
pca_prcomp <- prcomp(qdat, scale. = TRUE)
eigenvalue <- pca_prcomp$sdev^2
eigenvalue_rounded <- round(eigenvalue, digits = 2)
PoV <- pca_prcomp$sdev^2/sum(pca_prcomp$sdev^2)
cumsum(PoV)

#tabulation
matrix <- matrix(c(eigenvalue, PoV*100 , cumsum(PoV)*100), ncol = 3)
colnames(matrix) <- c("Eigenvalue", "PoV", "Cum. Sum")
PoV_rounded <- round(matrix, digits = 2)
#three PC's
PoV_rounded[1:3,]


#PCA plots

# loadings or weights
loadings <- pca_prcomp$rotation 
round(loadings, 3)

eigs <- eigenvalue
eigs_perc <- 100 * eigs / sum(eigs)
eigs_cum <- cumsum(eigs_perc)

eigs_df <- data.frame(
  eigenvalue = eigs,
  percentage = eigs_perc,
  'cumulative percentage' = eigs_cum
)

print(round(eigs_df, 4), print.gap = 2)

plot(pca_prcomp$x, type = "n", las = 1)
abline(h = 0, v = 0)
points(pca_prcomp$x[ ,1], pca_prcomp$x[ ,2], pch = 19, 
       col = "#88888877")
title(main = "PC Plot of Customers")


plot(loadings[,1], loadings[,2],
     xlim=c(-1,1), ylim=c(-1,1),
     main='Loadings for PC1 vs. PC2',
     xlab="PC1", ylab="PC2")

biplot(pca_prcomp, scale = 0, main = "Biplot")
```
