---
title: "hw04"
author: "Josh Seo"
date: "4/10/2018"
output: github_document
---

```{r Prep}
source('../code/archive-functions.R')
knitr::opts_chunk$set(echo = TRUE, error = TRUE, fig.path = '../images/')
```

```{r part1.4}
raw_data <- read_archive('stringr')
clean_data <- clean_archive(raw_data)
plot_archive(clean_data)
```

```{r part1.5}
raw_data_dplyr <- read_archive('dplyr')
clean_data_dplyr <- clean_archive(raw_data_dplyr)
plot_archive(clean_data_dplyr)
write.table(clean_archive(raw_data_dplyr), file = "../data/dplyr-archive.csv", 
            sep = ",",
            col.names = TRUE,
            row.names = FALSE)



raw_data_ggplot <- read_archive('ggplot2')
clean_data_ggplot <- clean_archive(raw_data_ggplot)
plot_archive(clean_data_ggplot)
plot_archive(clean_data_ggplot)

write.table(clean_archive(raw_data_ggplot), file = "../data/ggplot-archive.csv", 
            sep = ",",
            col.names = TRUE,
            row.names = FALSE)



raw_data_XML <- read_archive('XML')
clean_data_XML <- clean_archive(raw_data_XML)
plot_archive(clean_data_XML)
plot_archive(clean_data_XML)

write.table(clean_archive(raw_data_XML), file = "../data/xml-archive.csv", 
            sep = ",",
            col.names = TRUE,
            row.names = FALSE)



raw_data_knitr <- read_archive('knitr')
clean_data_knitr <- clean_archive(raw_data_knitr)
plot_archive(clean_data_knitr)
plot_archive(clean_data_knitr)

write.table(clean_archive(raw_data_knitr), file = "../data/knir-archive.csv", 
            sep = ",",
            col.names = TRUE,
            row.names = FALSE)

#merge dataframe
library(ggplot2)
combined_data <-
  rbind.data.frame(clean_data_dplyr, clean_data_ggplot, clean_data_XML, clean_data_knitr)

#merged plot
ggplot(combined_data, aes(x = date, y = size)) +
  geom_step(aes(col = name)) +
  ggtitle("timeline of version sizes") +
  xlab("date") + ylab("Size (KB)")


#faceted plot
ggplot(combined_data, aes(x = date, y = size)) +
  geom_step(aes(col = name)) +
  facet_wrap(~name, scales="free") +
  ggtitle("timeline of version sizes") +
  xlab("date") + ylab("Size (KB)")

```


```{r part 3.1}
tweet <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-spring-2018/master/data/text-emotion.csv", stringsAsFactors = FALSE)

#count the number of characters per tweet 
chars_per_tweet <- nchar(tweet$content)
summary(chars_per_tweet)

#plot a histogram 
hist(chars_per_tweet,
     main = "Histogram of number of characters in tweet",
     xlab = "Number of Characters",
     col = "lavender",
     xlim = c(0, 200),
     breaks = 50)
```

```{r part 3.2}
library(stringr)
#mention counts and plot
mention <- str_extract_all(tweet$content, '@[\\w]{1,16}[\\w]{1,16}')
mention_count <- sapply(mention, length)
mention_table <- table(mention_count)
mention_table
barplot(mention_table)


#tweet with 10 mentions
i <- which.max(mention_count)
mention[i]

```


```{r part 3.3}
#number of hash tags
hash_tags <- str_extract_all(tweet$content, pattern = "#[[:alnum:]]{1,}[[:alnum:]]{1,}")
hash_count <-sapply(hash_tags, length)
hash_table <- table(hash_count)
barplot(hash_table)
mean(hash_count)

#length of hash tags
hash_tags[1]

hash_only <- str_replace_all(hash_tags, "[character(0)]", "")
tags_only <- str_replace_all(hash_only, "[#]", "")
hash_length <- nchar(tags_only, type = "chars", allowNA = FALSE)
mean(hash_length)
table(hash_length)
which.max(hash_length)
```

