---
title: "hw02 shot charts"
author: "Josh Seo"
date: "Mar. 5, 2018"
output: github_document
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE, fig.path = '../images/')
library(readr)
library(ggplot2)
library(dplyr)
library(grid)
```
#PART 5.1
```{r}
shots_data <- read.csv(file = "../data/shots-data.csv", stringsAsFactors = FALSE)
shots_data %>%
  filter(shot_made_flag=="made_shot" | shot_made_flag=="missed_shot") %>%
  group_by(name)%>%
  summarise(total = n()) %>% 
  ungroup() %>% 
  arrange(desc(total))
```
#PART 5.2: Total (2PT+3PT) effective
```{r}
shots_data %>%
  filter(shot_made_flag=="made_shot" | shot_made_flag=="missed_shot") %>%
  group_by(name)%>%
  summarise(total = n()) %>% 
  ungroup() %>% 
  arrange(name) %>%
  data.frame -> data_1

shots_data %>%
  filter(shot_made_flag=="made_shot") %>%
  group_by(name)%>%
  summarise(made = n()) %>% 
  ungroup() %>% 
  arrange(name) %>%
  data.frame -> data_2


shots_data %>%
  filter(shot_made_flag=="missed_shot") %>%
  group_by(name)%>%
  summarise(missed = n()) %>% 
  ungroup() %>% 
  arrange(name) %>%
  data.frame -> data_3
perc_made <- (data_2$made/data_1$total)
cbind(data_1, select(data_2, made), perc_made) -> effective_shooting
arrange(effective_shooting, desc(perc_made))
```

#PART 5.2: 2PT effective
```{r}
shots_data %>%
  filter((shot_type=="2PT Field Goal" & shot_made_flag=="missed_shot") | (shot_type=="2PT Field Goal" & shot_made_flag=="made_shot")) %>%
  group_by(name)%>%
  summarise(total_2PT = n()) %>% 
  ungroup() %>% 
  arrange(name) %>%
  data.frame -> data_1_2pt

shots_data %>%
  filter((shot_type=="2PT Field Goal" & shot_made_flag=="made_shot")) %>%
  group_by(name)%>%
  summarise(made = n()) %>% 
  ungroup() %>% 
  arrange(name) %>%
  data.frame -> data_2_2pt

perc_made_2pt <- (data_2_2pt$made/data_1_2pt$total)
cbind(data_1_2pt, select(data_2_2pt, made), perc_made_2pt) -> effective_shooting_2pt
arrange(effective_shooting_2pt, desc(perc_made_2pt))
```
#PART 5.2: 3PT effective
```{r}
shots_data %>%
  filter((shot_type=="3PT Field Goal" & shot_made_flag=="missed_shot") | (shot_type=="3PT Field Goal" & shot_made_flag=="made_shot")) %>%
  group_by(name)%>%
  summarise(total_3PT = n()) %>% 
  ungroup() %>% 
  arrange(name) %>%
  data.frame -> data_1_3pt

shots_data %>%
  filter((shot_type=="3PT Field Goal" & shot_made_flag=="made_shot")) %>%
  group_by(name)%>%
  summarise(made = n()) %>% 
  ungroup() %>% 
  arrange(name) %>%
  data.frame -> data_2_3pt

perc_made_3pt <- (data_2_3pt$made/data_1_3pt$total)
cbind(data_1_3pt, select(data_2_3pt, made), perc_made_3pt) -> effective_shooting_3pt
arrange(effective_shooting_3pt, desc(perc_made_3pt))
```
#Part 6.1
```{r}
    shots_data %>%
      group_by(shot_distance) %>%
      select(shot_distance, shot_made_flag) %>%
      summarise(
        made_shot_prop = (sum(shot_made_flag == 'made_shot'))/(sum(shot_made_flag == 'made_shot'|shot_made_flag == 'missed_shot')))

```

#Part 6.2
```{r}
shot_distance_table <- data.frame(
      shots_data %>%
      group_by(shot_distance) %>%
      select(shot_distance, shot_made_flag) %>%
      summarise(made_shot_prop = 
                  (sum(shot_made_flag == 'made_shot'))/
                  (sum(shot_made_flag == 'made_shot'|shot_made_flag == 'missed_shot'))
                )
)
    
ggplot(shot_distance_table, aes(x=shot_distance, y=made_shot_prop)) + geom_point(size=4, shape=20)

shot_distance_table$shot_distance[shot_distance_table$made_shot_prop >= 0.50]

```

#Part 7
```{r}
part7 <- data.frame(
  shots_data %>%
    group_by(minute, name) %>%
    select(name, minute, shot_made_flag) %>%
    summarise(total_numberofshots = sum(shot_made_flag == "made_shot"|shot_made_flag=="missed_shot"))
)

ggplot(part7, aes(x = minute, y = total_numberofshots)) +
  geom_point() +
  geom_path() +
  geom_rect(aes(xmin = 1, xmax = 12, ymin = 1, ymax = 60), color="magenta", alpha = 0.01) +
  geom_rect(aes(xmin = 25, xmax = 36, ymin = 1, ymax = 60), color="magenta", alpha = 0.01) +
  scale_x_continuous() +
  theme_minimal() +
  facet_wrap(~name)

```
